export const CREATE_BILL_ERROR = 'CREATE_BILL_ERROR';
export const CREATE_BILL_SUCCESS = 'CREATE_BILL_SUCCESS';

export const DELETE_BILL_ERROR = 'DELETE_BILL_ERROR';
export const DELETE_BILL_SUCCESS = 'DELETE_BILL_SUCCESS';

export const UNDELETE_BILL_ERROR = 'UNDELETE_BILL_ERROR';

export const UPDATE_BILL_ERROR = 'UPDATE_BILL_ERROR';
export const UPDATE_BILL_SUCCESS = 'UPDATE_BILL_SUCCESS';

export const FILTER_BILLS = 'FILTER_BILLS';
export const LOAD_BILLS_SUCCESS = 'LOAD_BILLS_SUCCESS';
export const UNLOAD_BILLS_SUCCESS = 'UNLOAD_BILLS_SUCCESS';

export const SEARCH_BILLS = 'SEARCH_BILLS';
export const SEARCH_BILLS_ERROR = 'SEARCH_BILLS_ERROR';
export const SEARCH_BILLS_SUCCESS = 'SEARCH_BILLS_SUCCESS';
